apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.appName }}-{{ .Values.container.environment }}
  namespace: {{ .Values.container.namespace }}
  annotations:
    kubernetes.io/change-cause: "Deployed image tag {{ .Values.image.tag }}"
spec:
  replicas: {{ .Values.replicas.nginx }}
  selector:
    matchLabels:
      app: {{ .Values.container.appName }}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-{{ .Values.container.environment }}-{{ .Values.container.appName }}: "{{ .Values.vault.secretLocation }}"
        vault.hashicorp.com/agent-inject-template-{{ .Values.container.environment }}-{{ .Values.container.appName }}:
        {{ toYaml .Values.vault.vaultSecretTemplate | indent 8 }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: app-role
      labels:
        app: {{ .Values.container.appName }}
    spec:
      containers:
        - name: {{ .Values.container.appName }}-{{ .Values.container.environment }}-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http-port
            containerPort: 80
        resources:
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
