{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.container.appName }}-{{ .Values.container.environment }}-autoscale
  namespace: {{ .Values.container.namespace }}
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Min
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.container.appName }}-{{ .Values.container.environment }}
  minReplicas: {{ .Values.replicas.nginx }}
  maxReplicas: {{ .Values.hpa.nginx.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: {{ .Values.hpa.nginx.type }}
        averageUtilization: {{ .Values.hpa.nginx.value }}
{{- end }}
