---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: muffin-developers
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: muffin-developers-rolebinding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: muffin-developers
subjects:
  - kind: Group
    name: muffin:developers

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: muffin-github
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments", "jobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: muffin-github-rolebinding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: muffin-github
subjects:
  - kind: Group
    name: muffin:github
